apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-runner
spec:
  selector:
    matchLabels:
      app: schedule-runner
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: schedule-runner
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: schedule-runner
          image: nodescript-backend
          workingDir: /app/packages/schedule-runner
          command:
            - node
            - out/bin/http.js
          ports:
            # - name: http
            #   containerPort: 8080
            - name: aux
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              memory: 1000Mi
          env:
            # - name: HTTP_PORT
            #   value: '8080'
            - name: AUX_HTTP_PORT
              value: '8081'
            - name: INVOKE_TIERS
              valueFrom:
                configMapKeyRef:
                  name: schedule-runner-tiers
                  key: tiers.json
          envFrom:
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
