apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: relay-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: relay-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: relay-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: relay-service
  template:
    metadata:
      labels:
        app: relay-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: HTTP_PORT
          value: "8080"
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: relay-secrets
        image: ghcr.io/nodescriptlang/relay-service:1.9.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: relay-service
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: relay-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: relay-service
