apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  destinations:
  - namespace: default
    server: '*'
  - namespace: argocd
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/backend/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-domain-mapping
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/custom-domain-mapping/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fetch-service
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/fetch-service/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/frontend/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guides
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/guides/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: apps
  source:
    path: apps/routing-apps/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
