apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-cache-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`CACHE_SERVICE_HOST`)
      kind: Rule
      services:
        - name: cache-service
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
