apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-docs
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`DOCS_HOST`)
      kind: Rule
      services:
        - name: docs
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
