apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-docs
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`DOCS_HOST`)
      services:
        - name: docs
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
