apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-fetch-service
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`FETCH_SERVICE_HOST`)
      kind: Rule
      services:
        - name: fetch-service
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
