apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-gateway-service
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`[0-9a-z-]+.INVOKE_HOST`)
      priority: 1000
      services:
        - name: gateway-service
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
