apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-gateway-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`w8132bq0.run.nodescript.dev`)
      kind: Rule
      services:
        - name: backend-invoke
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
