apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-guides
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`GUIDES_HOST`)
      services:
        - name: guides
          port: 8900
  tls:
    secretName: nodescript-dev-certificate
