apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-payment-provider-service
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`PAYMENT_PROVIDER_SERVICE_HOST`)
      services:
        - name: payment-provider-service
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
