apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-relay-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostRegexp(`{subdomain:[0-9a-z-]+}.INVOKE_HOST`)
      kind: Rule
      services:
        - name: relay-service
          port: 8080
  tls:
    secretName: nodescript-dev-certificate
