apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: automation-cloud-certificate
  namespace: default
spec:
  dnsNames:
  - automation.cloud
  - '*.automation.cloud'
  - '*.smartfeed.automation.cloud'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: automation-cloud-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-custom-automation-cloud-services
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{subdomain:[0-9a-z-]+}.automation.cloud`)
    services:
    - name: gateway-service
      port: 8080
  - kind: Rule
    match: HostRegexp(`{subdomain:[0-9a-z-]+}.smartfeed.automation.cloud`)
    services:
    - name: gateway-service
      port: 8080
  tls:
    secretName: automation-cloud-certificate
