apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-cd
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`cd.ns.ubio.dev`)
    priority: 10
    services:
    - name: argocd-server
      namespace: argocd
      port: 80
  - kind: Rule
    match: Host(`cd.ns.ubio.dev`) && Headers(`Content-Type`, `application/grpc`)
    priority: 11
    services:
    - name: argocd-server
      namespace: argocd
      port: 80
      scheme: h2c
  tls:
    secretName: ubio-dev-certificate
