apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-api-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`api.staging.nodescript.dev`) && Path(`/ws`)
    services:
    - name: api-service
      port: 8080
  - kind: Rule
    match: Host(`api.staging.nodescript.dev`)
    services:
    - name: api-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-capture-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`capture.staging.nodescript.dev`)
    services:
    - name: capture-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-fetch-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`fetch.staging.nodescript.dev`)
    services:
    - name: fetch-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-frontend
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`staging.nodescript.dev`)
    services:
    - name: frontend
      port: 8080
  - kind: Rule
    match: Host(`embed.staging.nodescript.dev`)
    services:
    - name: frontend
      port: 8080
  - kind: Rule
    match: HostRegexp(`{subdomain:[0-9a-zA-Z_-]+}.edge.staging.nodescript.dev`)
    services:
    - name: frontend
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-gateway-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HostRegexp(`{subdomain:[0-9a-z-]+}.run.staging.nodescript.dev`)
    priority: 1000
    services:
    - name: gateway-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-guides
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`docs.staging.nodescript.dev`)
    services:
    - name: guides
      port: 8900
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-payment-provider-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`payment-provider.staging.nodescript.dev`)
    services:
    - name: payment-provider-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-registry-service
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`registry.staging.nodescript.dev`)
    services:
    - name: registry-service
      port: 8080
  tls:
    secretName: nodescript-dev-certificate
