apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8082"
  name: traefik
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: traefik
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --serversTransport.insecureSkipVerify=true
        - --accesslog
        - --entryPoints.metrics.address=:8082
        - --entrypoints.websecure.Address=:443
        - --entrypoints.web.Address=:80
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.web.http.redirections.entryPoint.scheme=https
        - --entrypoints.web.http.redirections.entrypoint.permanent=true
        - --providers.kubernetescrd
        - --providers.kubernetescrd.allowCrossNamespace=true
        - --metrics=true
        - --metrics.prometheus=true
        - --metrics.prometheus.entryPoint=metrics
        image: traefik:2.10.5
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10s
        name: traefik
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /metrics
            port: 8082
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          procMount: Default
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        workload/ingress: "true"
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: traefik
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: traefik
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: default
spec:
  cipherSuites:
  - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
  - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
  minVersion: VersionTLS12
  preferServerCipherSuites: true
