apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 0
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        workload/monitoring: "true"
      securityContext:
        fsGroup: 472
        supplementalGroups: [0]
      volumes:
        - name: config
          configMap:
            name: grafana-config
      containers:
        - name: grafana
          image: grafana
          ports:
          - name: http
            containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /etc/grafana
          envFrom:
            - secretRef:
                name: grafana-secrets
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              memory: 1Gi
