apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: default
  name: nodescript-dev-certificate
spec:
  secretName: nodescript-dev-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - "nodescript.dev"
    - "*.nodescript.dev"
    - "*.edge.nodescript.dev"
    - "*.run.nodescript.dev"

    - "*.staging.nodescript.dev"
    - "*.edge.staging.nodescript.dev"
    - "*.run.staging.nodescript.dev"
