kind: Kustomization
namespace: invoke
images:
  - name: nodescript-invoke-service
    newName: eu.gcr.io/automation-cloud-registry/nodescript-invoke-service
    newTag: 2.1.3
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
