kind: Kustomization
namespace: invoke
images:
  - name: nodescript-invoke-service
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-invoke-service
    newTag: 2.1.12
resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
