kind: Kustomization
namespace: invoke
images:
  - name: nodescript-invoke-service
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-invoke-service
    newTag: 2.15.1
resources:
  - ./generated/deployment.yaml
  - ./generated/hpa.yaml
  - ./generated/pdb.yaml
  - ./generated/service.yaml
  - ../../custom
