version: "3"

includes:
  kustomize: ../../.tasks/kustomize.yaml
  sed: ../../.tasks/sed.yaml

vars:
  TARGETS: |
    production
  REPLACEMENTS: |
    production:API_SERVICE_HOST,api.nodescript.dev
    production:CACHE_SERVICE_HOST,cache.nodescript.dev
    production:CHAT_TO_WORKSPACE_HOST,chat.nodescript.dev
    production:DOCS_HOST,docs.nodescript.dev
    production:FETCH_SERVICE_HOST,fetch.nodescript.dev
    production:FRONTEND_EDGE_HOST,edge.nodescript.dev
    production:FRONTEND_HOST,nodescript.dev
    production:FRONTEND_NOTEBOOKS_HOST,notebooks.nodescript.dev
    production:GUIDES_HOST,guides.nodescript.dev
    production:INVOKE_HOST,run.nodescript.dev
    production:PAYMENT_PROVIDER_SERVICE_HOST,payment-provider.nodescript.dev
    production:REGISTRY_SERVICE_HOST,registry.nodescript.dev
    production:RELAY_SERVICE_HOST,relay.nodescript.dev

tasks:
  default:
    silent: true
    cmds:
      - task: kustomize:buildAll
        vars:
          TARGETS: "{{.TARGETS}}"
      - task: sed:replaceAll
        vars:
          REPLACEMENTS: "{{.REPLACEMENTS}}"
