apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-service
spec:
  replicas: 4
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fetch-service
  template:
    metadata:
      labels:
        app: fetch-service
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: "true"
      containers:
        - name: fetch-service
          image: nodescript-fetch-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
