kind: Service
apiVersion: v1
metadata:
  name: fetch-service
  annotations:
    metricsPort: "8080"
spec:
  type: ClusterIP
  selector:
    app: fetch-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
