apiVersion: apps/v1
kind: Deployment
metadata:
  name: capture-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capture-service
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: capture-service
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: capture-service
          image: nodescript-backend
          workingDir: /app/packages/capture-service
          command:
            - node
            - out/bin/http.js
          ports:
            - name: http
              containerPort: 8080
            - name: aux
              containerPort: 8081
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              memory: 200Mi
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: AUX_HTTP_PORT
              value: '8081'
          envFrom:
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
