kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: gcr.io/automation-cloud-registry/nodescript-backend
    newTag: 4.8.0
resources:
  - ../../base
  - ./pdb.yaml
  - ./hpa.yaml
