apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
spec:
  selector:
    matchLabels:
      app: cache-service
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      terminationGracePeriodSeconds: 60
      automountServiceAccountToken: false
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: cache-service
          image: cache-service
          ports:
            - name: http
              containerPort: 8080
            - name: aux
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: AUX_HTTP_PORT
              value: '8081'
          envFrom:
            - secretRef:
                name: cache-secrets
          readinessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
