apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: relay-secrets
stringData:
    JWT_PUBLIC_KEY: ENC[AES256_GCM,data:U3gfFizyEpAfgoPUx77U+IB4DoKNTUqJIwCSg91d0g4G3OT+Vpbw0XX7Qu06M49Zf8Cnkc/W4FYqWybEOSIJU56RjUFI7iAM98STrdSfcqe7DR1dxZ/MtyWQ7V9mFJhNGkkY5oepQ+q7jhRvSjDOPkn1rMJqDsQZNiAeO5JZ6RsGQMOCbm3WLcGEU+JOT0eYRlRFdCZROLu7WZM22YuWTIwzCOwl0rMFjNFEdn7WH5wAKJSsaZvvHMOxMqbnQo1Kz0nBssL0R0A0AiY9J+3dSZPzBLd1cilvAEH5jLocebH6VYtiYXt4rbB5IMQBq20cnmQ4YH5XC6YSX0ZgpTlaCAcCWoL7HJguHcbDsabXZwy+ihEfm1iRRPg5GnlV3ZjOXpb+sZ39Fb958dqqY8dJx/2YajzIzsUf4uYoextIicZTodVoabXFKmEvUWRXILPTAKNdk/KDpxEzH9bbwKXdxHuBbGiISQLXitgRov3rjE4f7ItRDRf2+BA2PmGOjoiN8wlq3vT/jH3W0SwKCAZZbDqV5w9G8pUWbyPHR2RjyqPMx7e1lbxe/9BKUUoyxNl/ENhXzEuDXR2Ff2hCP4W0SiHL7g==,iv:4eXbH34LjWBzul12kPnpst5Ar+U514kA6sstYRIfjqs=,tag:tVxkA06HEFVEEYEg24N/SA==,type:str]
    LLM_PRICE_PER_CREDIT: ENC[AES256_GCM,data:gZ5mm/pecA==,iv:10bvJI1OPF1a7wDeDCHv3REc1Gms6RiydrtTV6+rL7w=,tag:JDc4x9NOpzrKXPCFlUzCaw==,type:str]
    LLM_OPENAI_API_KEY: ENC[AES256_GCM,data:7Q52ajjIRa/wEWQ9Z1xpnD7AQY1pbj0VFzcPAkIqN4637/sta4o1/roKkDAT5IfX0dKmvUUF38/xYb1ynArhKo4aIJXkaJ7LSSh0RevjvI5vj86D9+nLVNbqq/Am6KB1/daRvqW6jRfmFiHgsPrmy//ovxJ8XdWq/+ZYqyTjzsva5Abfs/hSlkBycnx1yZoFAY7oFjTV7IMhsaNa3IyFzQ+mJdw=,iv:GC7+uMNQn+Sp+tHzNL2gwMwDUJCtAkj2vb5QgDOyeqc=,tag:W2pMCZu5fLmvtnaJtFDBsA==,type:str]
    LLM_ANTHROPIC_API_KEY: ENC[AES256_GCM,data:5tumDrF3WC/vRd9FGJS0OBMWebLhyiLYeHI8Boq/SKZuRRh3f82Yx2ye1L2Cg8T2rke1tWHCskxZVXpBEM3Vyvffzhmq3TOIMSOjPv6ctIn+oODHdBM1xJu6kBdtOpya0ErL0hPK8G52bwbd,iv:XmfNb6+wJH4GQ8F/3Qc51KiAlhaZs5hDGCXPE3vFAPw=,tag:7ZjfzUL1/qxcqmJSwY/urw==,type:str]
    LLM_GEMINI_API_KEY: ENC[AES256_GCM,data:VBs8hXI5veIlsFD3ax2UHv3eJdHigh6HrGOk+kqnhdIWdRkLTPD2,iv:Kl2eEd5pVlXNZcZUPoHput1GOeL6YvUkaky5oXazIUY=,tag:IP7oJtgC3HnmiijiBdQj+Q==,type:str]
    LLM_GROQ_API_KEY: ENC[AES256_GCM,data:uUXmPjKshIQdDjy7kE05kNIoBZSby1H291yH86w9ZRUbkt/pvlOdKqEga3WX93vurDFRFt3Bftc=,iv:G24I7oB8BFgRYRfq/6tKs5sGQo73V0gmbLGu/oPYxgg=,tag:3B32/YYVaSj9vE8uAWip9g==,type:str]
    LLM_DEEPSEEK_API_KEY: ENC[AES256_GCM,data:/wE7cGhZvrThCjUh949tsxqehGoLetbDVE8f+9UZIx51g8g=,iv:XMXGoqqP0Tu/K4zhI57s+Mbb9KAX+H+quPvMNY9Kpok=,tag:qS08ld0KtcMvekAlG5DeMQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2025-02-19T15:39:53Z"
          enc: CiQAlXZeeQ2auFhPnK6Lr0ovdomJv03hGaAGQfiDa1p4b6OlacISSQBnOh035zGAhZnEbjNSVARUBZcdCsKi+t6eZAempDKElOuIPQe1K0JFWS55AVkfBfrtjDVTJdxZG57P8K1yNI70wkfh15Fd5y8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-19T20:52:04Z"
    mac: ENC[AES256_GCM,data:srb0i/1D/hy1PMBuEfxplMwYYaF2kmkedNrZdJoEwWw24RIl5KVw3sxuWOIVy0z9w5tXPYLM/4FjPYK9/BC/loOGAG2I6wR1SjeSTtZzqB/Rjy3fQP+oKY9RseeukCcwjs2aSQzMHsaDHxzxbIjYUyAByVLB3OdffoOs7HjIqCk=,iv:d2mE+uVeLRQ3axVWAF5JWFpA0tJfDmEDLZQpDOURysM=,tag:BNfLYTehN95qz2n8ssFKkw==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.9.1
