apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: relay-secrets
stringData:
    SERVICE_PROVIDERS: ENC[AES256_GCM,data:4h6Z7CicTBGt6qP5V5ztLwTqwQBmv4c3yTrKwWVaABaQ+R7Qx4VRQu+Xnd9oowVaVm818/2Mia1CpZJcE59l9E2o7Ciby3Y2KKmbcNKC1ZyYPoKUZVW1meU8k6PeV0OwWpKxbS9yRFVd+vx5TMH9sjLcU+YPclgor+YqPYgZVAKnuIwdklAaCPBEyOnNV4XC7TPUNrpeDkIQuom7wieIWqGV/92U0nwijiNNB6Mn7Z/0E6XVOptUzQ8yj5R6gU1kKhKgqPZeYLdPAPtEMGnN6Z6wyBe/AHZFftnUZSu6nTkVp5FzwNdf0FifBjdFfbsTHcJmZvUqTwTfysfTw79EVrUTtJ3eMC1/zg9CzwAcVVDSYdcBw1etXO/59vCvQA82Ndq0dMUSkM/xibAt87ZelypewzD8BlW2FahMdeXlAgf9tInmbHLo0oe/JRNBbbqM52IqtM/rKMc1taYwzdW065RVRFCfQnn5H5/em67czGqvIBui8iuW3jfWc4oTSJWLQj3/kAeDU8yax7/71oBAsP6yz/D0ErpuEyUu5+vJ8/pHUnao93iBPMAwHek+JCK/NPx3mlzzuDo3LDOnRzWXSFSDYUD0QEXXbZCbfodIk9dC1/r9RpJcC+Xq2hzoPYwrnyErPB3SfWTG4yYyn0n5Y+TPIXPFi/exHO2Czts63IiTAsPkD85pfm5lKYN2JEwPR9Kci4YhpIQkvATYb86QEgUlAtQTwj/1MduwZNs/f7yLhI1fa1o2UxjiK2+sam56iSupuJG5/jndiTlLVPwDRksjgy2oH/SD2TJudXQh6K1W+YqgG7NHd0VDJr+j1FkEK7K+NhVqyKM4cX4WmLQrBkt2lhv0ZaVCfNQnWj1CTVrCj1vGkcZWpyHU9SHjiw7YG2uCqB67vCaO5PKX76yC3EqiDLtnA5faeAiHRRiFhy7FUTbcZYTYgOV16wlvNIGO3B9Y1+wDz/FjwXG2kZrnAZOBz3ymSDONYdu3GzXiADcrCtuLw0M8C+QsdslLhrZ+ir3ZuUpvbNotCiCFvOHcvziA7HARS1UTRdMCX4/oZVuhWqcGTloiagoOxiCsVb0yGTbfWyhBDg4c9lK1E3LCrFTkLV+lzEot8sqaVffIKvFM2QAcMqlLcGJ5kT2xOKbj/m3yMk1HeD6vFdOc0RqDlD+uC21ygfa666Hr67Tzor5YOO0vNKyVZj56ESKte16L/c6fH8FcTrAdxGptbUc8lwQnFB8/rDM5G/U+TvlQzBmPJqpjoyOOLZ73Jvw+Q0ey1WJ/Qj83O3qz28xGR2rBC6TVfvRBRY9mnUqTT+xMbLWDs+YgXzN0WaHp6x5OS2q/Bg/7fUDf,iv:SM98OoLYcWzG0k4qNQWfzLsuoAMl8kBt1lr1GfapJGY=,tag:0BO+gFt65iBrZkJrabbPdg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2025-02-19T15:39:53Z"
          enc: CiQAlXZeeQ2auFhPnK6Lr0ovdomJv03hGaAGQfiDa1p4b6OlacISSQBnOh035zGAhZnEbjNSVARUBZcdCsKi+t6eZAempDKElOuIPQe1K0JFWS55AVkfBfrtjDVTJdxZG57P8K1yNI70wkfh15Fd5y8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-20T15:09:18Z"
    mac: ENC[AES256_GCM,data:WYumFltKEZFwWeBD5s1XM9RpBmaZn1rDNRuVjgLW7/6B14jkYf+r1pUbKJ+XB0YCD/GWtilQ7EZrR3BrCDPHw0zwHn6Eh3ytkTFfk7R3YWN63ZmDxBNJ+OcaqW5l+G2uWTLz9qYxqUAVs9IUw3pNBDdSHSdYH38caZeupiJfgk0=,iv:fC+J2vqkQf/pDFn2+4o/G5VHHNKiYH4VQ7Xzgu1oso0=,tag:hredgz/9z7s29aJuJ8Klug==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.9.1
