apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: relay-secrets
stringData:
    SERVICE_PROVIDERS: ENC[AES256_GCM,data:LHYKbFFuW+/G6ewjRxgJ51blU6kINQNJtcJLBbxVMHSCcr8+37atGZMKY1a655svfRXPA4xBL3F7xwPf1tPOhVwaql/wrNpisCKMF/HzdH7zE9d875Y+9nWZy/UBE6uN26NgVy/TqYUf73WtA9HlGW148GekZr5P8w418qI9tF0KXLu+cTWZWl2iR+UJTKNHhL7y562QRiEjEEpNrpDtl/OXsCnAOoA4EZVE5vdddecB4yk5/JDlOB8rMtFsfek3ALmVbQCwQXvMmSx46ofgEa1ExtNWIl8CvUHaiOtF0t9/du/NOokUv07lBqrdW8JwEl/SdPdUO4B6vri4d8sRJem4fQOKFO0hiVB7Tigi/qOxrdyLeRWNFnlOooPBvXPQesW/Qpbriq9Wt5Rbmth2bq9Bv8vGY1gvr79btuW3+bIO5nPEnefCFoqjLXGaPfwiTkXGqDLYCo4D6ATt7+Y8x0p9kuz2RAB8+Rz/BHD7/x8+4xTCynr3csxNeUshZAKyZmm1vcZ5uvby82dnl7cHznoxiN0IFazI9803V+QB4dwdWc+HlGelHxxntVQAWrYk568gTelZMy+cGGExnx/h5oeARIYWcAdxcWui9/akm97f+lrhBQ06IgkiVi4j2C5XOX6MW6OYLToqoDeG8E0R+rU+JjjrmJc4LSju1AQvmUzPk9Kh/i1WKefFCEbfuVYJ6VFoMaxFsbvjYR1It/HlTbZmFH330tR23gDetO8mQfyjUV/pdYMZAzZkGlHJJCUuZ6u9G229TyObJVDzLDMX/m++4pfCZgAPSuZ0H4ZuzG/fFjIGq01mczBJAvZxUNluQlEbg6ieaAFO+iZfojq/7ZqVMvyw6C1weHEj6mla/ogy8lwuIW2PIU8hnwQj2fAy98AsqowlgcHtkb+1RqEYBqPLd9RuVDcEDXTs4pl2NuONHZufxCHsojbj1yoaR4u1qfV3foIeNezhbfq53rD7NOtkCnt1qg==,iv:ZWKbfspSGkWS91E1BNKP1BsEFlV1cJz/DorGVlwugI0=,tag:cwwz6/4fx1FEviiK9uFTYw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2025-02-19T15:39:53Z"
          enc: CiQAlXZeeQ2auFhPnK6Lr0ovdomJv03hGaAGQfiDa1p4b6OlacISSQBnOh035zGAhZnEbjNSVARUBZcdCsKi+t6eZAempDKElOuIPQe1K0JFWS55AVkfBfrtjDVTJdxZG57P8K1yNI70wkfh15Fd5y8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-19T18:00:02Z"
    mac: ENC[AES256_GCM,data:mMTohxgFVnaomosGdYOZ3NzdRPRn85F0+Qys/zfBRv8SVPWFh5qQwnbXvANsZdr0VPHeO+v06w0jK+EybIGNkae9BjMVsNGxwNjhf3ASo3EKpqyK3pKqizBRVN0Z7D5kFtWmu2Teh9oRySUrjodZTM2DFidUY7GmmnsLmMaYxF0=,iv:CQ1V1wPO2mWTTUEIn1uVthRbxaeG2j2CDLT2C3TCmqw=,tag:jLxVj6/3nCDzdOJepzQNqg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.9.1
