apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: relay-secrets
stringData:
    VENDOR_CONFIG: ENC[AES256_GCM,data:P/j29lFtMT7prC0fOlSnKNtvu+Kh0HZJEz+4Sk4l8stz2y9EUsVueK5/qHDIT2f+pKvd6xdBWpW6luK9wEiLLabRDSRDq1BBevBvkquvZBTuTMApP4gRjsCiyA8LsA9GULsK2h6qD4yAWLuwpZclK+/YO8Jctrp8mL5UqcugprNIJohGNUm0Wp26e2Xm4qNgVzUUF2hj3tyw6MVamGZshZet1pbPbFFYFQgvijNNcsNZEYiPSJ/H/JM+W7e7SkyC/3bmunhbIYEH4JmVTxWq/HOjBvTOGh33SlAzj28RxGOVb8yjBA/tSADvZBsDQEhWm2JZE4Ell1pdUl5Pw+8EtWL0bFlu+SM+Dm52GnHTU6zemltx15KJ8vXiJsULWbaYJVqU+fQbFQizVoGcl9Y7hu08Iyw7us4NZIR1AqEwIIAh+NZorIi5z50sPBv9YgMPtCRpdf7y5mjQLcWpK7kCSNM5v/8VSLWuinemQ+qXVHOeVMI0i3yASZ7hX/K3y0M7phYrk8uX+LAnFHEUbh6DgRSVa5G2+JJRhIotlWljvLaIbJX+6JYYbqkXAMEUXQl7Fbth+aEUZ8uFPa1PES56Wm+3mH+PYdfLiQlMet0ik5FHJKmu3bRG/onSfJSWtl9/b1ekortCf/wlaAG3V+VDpFrUcuyATeIcGIX9QctPutrzugL/ZLNbueNF0PoD7efwbfG39Pyv6yu4CK0rHvB4IBJHhaqbT/qgyr7y2dlRC1/9t8B+/TQmAYSsGZIpZWBCXhhqY8kCkVatyEFBPQPGcgc1LCgv+sPUuw4kRBLIMqZq22V0APmiPDT8CXUnv6z4N6QSn3FdwFfKxdDeT37B2vYugXVl8SLZlzDTT/7QEuHcPAbI3OEkshyz5k5J275WuD3p7+birdOVFFjUjXimjKRrLXqnjUjZGBO3aFswFw==,iv:nxveuNWgBKiH86dIFJe47SvpmDSUHVjk2ZIP0+CtLN8=,tag:4UyijdliCU09gbp8Ab/Apw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2025-02-19T15:39:53Z"
          enc: CiQAlXZeeQ2auFhPnK6Lr0ovdomJv03hGaAGQfiDa1p4b6OlacISSQBnOh035zGAhZnEbjNSVARUBZcdCsKi+t6eZAempDKElOuIPQe1K0JFWS55AVkfBfrtjDVTJdxZG57P8K1yNI70wkfh15Fd5y8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-19T16:03:32Z"
    mac: ENC[AES256_GCM,data:oFxtr1Go+XrHe1XkzW1sxnn0qp3apOv3zWrATP2NHnsgeL/oyqfUyh4u3M6M2o5jQtePUbFWSES3Xc/6Mw4rs6noQC1bQClEB05YpLG5dFSDesAI+mFbvxdvZ9Qota6lbkEWFBmXUfGbAVJ8YDthnAKcTnoKatk4Tngx6DQNedE=,iv:A40fWX1M6gDNL4TPhswkfGulL1MBrr1TkZFdUiEyH9U=,tag:Pb5SnfX7RvbvmwNC56gIKQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.9.1
