apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: payment-provider-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: payment-provider-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: payment-provider-service
  template:
    metadata:
      labels:
        app: payment-provider-service
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - node
        - out/bin/run.js
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: backend-secrets
        image: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend:4.40.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: payment-provider-service
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 400Mi
        workingDir: /app/packages/payment-provider-service
      imagePullSecrets:
      - name: gcp-registry-secret
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-provider-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-provider-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-provider-service
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-provider-service
