apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: route-infra-grafana
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`GRAFANA_HOST`)
      services:
        - namespace: monitoring
          name: grafana
          port: 3000
  tls:
    secretName: ubio-dev-certificate
