apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-infra-prometheus
spec:
  entryPoints:
    - websecure
  routes:
    - match: (Host(`PROMETHEUS_HOST`))
      kind: Rule
      services:
        - namespace: monitoring
          name: prometheus
          port: 9090
  tls:
    secretName: ubio-dev-certificate
