kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend
    newTag: 6.2.2
resources:
  - ../../base
  - ./pdb.yaml
  - ./hpa.yaml
