apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: invoke-group-ubio-flight-search
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoke-group-ubio-flight-search
  minReplicas: 10
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
