apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-background
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-background
  template:
    metadata:
      labels:
        app: backend-background
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: backend-background
          image: nodescript-backend
          command:
            - node
            - out/bin/background.js
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
            # TODO re-enable after k8s 1.25 is available
            # terminationGracePeriodSeconds: 1
