apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
spec:
  selector:
    matchLabels:
      app: backend-api
  replicas: 3
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      terminationGracePeriodSeconds: 60
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: backend-api
          image: nodescript-backend
          command:
            - node
            - out/bin/api.js
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 400Mi
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
