kind: Service
apiVersion: v1
metadata:
  name: backend-background
  annotations:
    metricsPort: "8080"
spec:
  type: ClusterIP
  selector:
    app: backend-background
  ports:
    - name: http
      port: 8080
      targetPort: 8080
