kind: Service
apiVersion: v1
metadata:
  name: backend-api
  annotations:
    metricsPort: '8080'
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
