kind: Service
apiVersion: v1
metadata:
  name: registry-service
spec:
  type: ClusterIP
  selector:
    app: registry-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: registry-service-aux
  labels:
    monitor: "true"
spec:
  type: ClusterIP
  selector:
    app: registry-service
  ports:
    - name: aux
      port: 8081
      targetPort: 8081
