kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: gcr.io/automation-cloud-registry/nodescript-backend
    newTag: 4.12.0
resources:
  - ../../base
  - ./pdb.yaml
configMapGenerator:
  - name: backend-config
    literals:
      - API_PREFIX=/~api
      - API_URL=https://api.nodescript.dev
      - CAPTURE_PREFIX=/~capture
      - DEPLOYMENT_GCP_CONTAINER_IMAGE=gcr.io/automation-cloud-registry/nodescript-service-runner
      - DEPLOYMENT_GCP_SERVICE_ACCOUNT=nodescript-platform@automation-cloud-production.iam.gserviceaccount.com
      - GCLOUD_ARTIFACTS_BUCKET=nodescript-platform-artifacts
      - GCLOUD_LOCATION=europe-west1
      - GCLOUD_PROJECT_ID=automation-cloud-production
      - GRAPH_CAPTURE_URL=https://capture.run.nodescript.dev/g/{graphId}
      - GRAPH_SOURCE_URL=https://nodescript.dev/graph/{graphId}
      - HUB_PREFIX=/~api
      - INVOKE_PREFIX=/~invoke
      - INVOKE_RECYCLE_THRESHOLD=20000
      - LOG_LEVEL=info
      - NS_ENV=production
      - NS_FRONTEND_URL=https://nodescript.dev
      - REGISTRY_PREFIX=/~registry
      - REGISTRY_URL=https://registry.nodescript.dev
      - WORKSPACE_DOMAIN_PATTERN={id}.run.nodescript.dev
