apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-background
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend-background
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-invoke
spec:
  minAvailable: 4
  selector:
    matchLabels:
      app: backend-invoke
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-registry
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend-registry
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-schedule
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend-schedule
