apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: background-service
  namespace: default
spec:
  ports:
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: background-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: background-service
  template:
    metadata:
      labels:
        app: background-service
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - node
        - out/bin/run.js
        env:
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: backend-secrets
        image: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend:5.27.6
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: background-service
        ports:
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 200Mi
        workingDir: /app/packages/background-service
      imagePullSecrets:
      - name: gcp-registry-secret
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: background-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: background-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: background-service
  namespace: default
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 95
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: background-service
