apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-secret
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: gateway-service
          image: nodescript-backend
          workingDir: /app/packages/gateway-service
          command:
            - node
            - out/bin/run.js
          ports:
            - name: http
              containerPort: 8080
            - name: aux
              containerPort: 8081
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              memory: 1000Mi
          env:
            - name: HTTP_PORT
              value: '8080'
            - name: AUX_HTTP_PORT
              value: '8081'
            - name: INVOKE_TIERS
              valueFrom:
                configMapKeyRef:
                  name: gateway-service-tiers
                  key: tiers.json
          envFrom:
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
