apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: dev@ub.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-private-key
    solvers:
      - dns01:
          # cnameStrategy: Follow
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-tokens
              key: token-all-zones
            email: dev@ub.io
