apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: invoke-group-$TIER-$GROUP
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoke-group-$TIER-$GROUP
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 95
