kind: Service
apiVersion: v1
metadata:
  name: invoke-group-$TIER-$GROUP
  annotations:
    metricsPort: "8081"
spec:
  type: ClusterIP
  selector:
    app: invoke-group-$TIER-$GROUP
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: aux
      port: 8081
      targetPort: aux
