apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: cache-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: cache-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: HTTP_PORT
          value: "8080"
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: cache-secrets
        image: ghcr.io/nodescriptlang/cache-service:1.8.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: cache-service
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cache-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cache-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cache-service
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cache-service
