apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This makes prometheus kill existing pods before adding new ones
      # It means Prometheus downtime but works well with FS-based locks
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        workload/monitoring: "true"
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       - topologyKey: kubernetes.io/hostname
      #         labelSelector:
      #           matchLabels:
      #             app: prometheus
      serviceAccountName: prometheus
      automountServiceAccountToken: true
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: prometheus-storage
        - name: config
          configMap:
            name: prometheus-config
        - name: secrets
          secret:
            secretName: prometheus-secrets
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: prometheus
          image: prometheus
          args:
            - --config.file=/etc/prometheus/prometheus-config.yaml
            - --web.config.file=/secrets/web.yaml
            - --storage.tsdb.path=/data/prometheus
            - --storage.tsdb.retention.time=RETENTION_TIME
            - --storage.tsdb.retention.size=RETENTION_SIZE
          ports:
          - containerPort: 9090
          volumeMounts:
            - name: storage
              mountPath: /data/prometheus
            - name: config
              mountPath: /etc/prometheus
            - name: secrets
              mountPath: /secrets
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              memory: 2Gi
          securityContext:
            runAsUser: 1000
            procMount: Default
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
