apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus
spec:
  # Do not allow to move Prometheus between nodes
  maxUnavailable: 0
  selector:
    matchLabels:
      app: prometheus
