apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus
spec:
  # Prometheus can be down when node is undergoing maintenance
  minAvailable: 0
  selector:
    matchLabels:
      app: prometheus
