global:
  scrape_interval: 15s
  external_labels:
    project: nodescript

scrape_configs:
  - job_name: "k8s-services"
    kubernetes_sd_configs:
      - role: endpoints
    # See https://github.com/prometheus/prometheus/blob/main/documentation/examples/prometheus-kubernetes.yml
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_annotation_metricsPort]
        action: keep
        regex: (\d+)
      - source_labels: [__address__, __meta_kubernetes_service_annotation_metricsPort]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
