global:
  scrape_interval: 15s
  external_labels:
    project: secure-vault

scrape_configs:
  - job_name: 'k8s-services'
    kubernetes_sd_configs:
      - role: endpoints
        # Note: this does not work as expected, use relabel_configs to filter services
        # selectors:
        #   - role: service
        #     label: "monitor=true"
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_monitor]
        action: keep
        regex: "true"
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: service
