apiVersion: v1
data:
  GRAPH_SOURCE_URL: https://nodescript.dev/graph/{graphId}
  LOG_LEVEL: info
  NS_FRONTEND_URL: https://nodescript.dev
  REGISTRY_URL: https://registry.nodescript.dev
  STRIPE_BILLING_PORTAL_ID: bpc_1P1CjOK3j0VnFpMHImKAuxrn
  WORKSPACE_DOMAIN_PATTERN: '{id}.run.nodescript.dev'
kind: ConfigMap
metadata:
  name: api-service-config-gk5774fgt5
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: api-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: api-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - node
        - out/bin/run.js
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: api-service-config-gk5774fgt5
        image: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend:6.6.2
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: api-service
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
        workingDir: /app/packages/api-service
      imagePullSecrets:
      - name: gcp-registry-secret
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 60
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-service
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-service
