apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: frontend
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
      - image: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-frontend:5.5.2
        name: frontend
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 50m
            memory: 400Mi
      imagePullSecrets:
      - name: gcp-registry-secret
      nodeSelector:
        workload/default: "true"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
