apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: frontend
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      automountServiceAccountToken: false
      containers:
      - image: gcr.io/automation-cloud-registry/nodescript-frontend:4.5.6
        name: frontend
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcp-registry-access
      nodeSelector:
        workload/default: "true"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
