apiVersion: v1
kind: Service
metadata:
  name: guides
  namespace: default
spec:
  ports:
  - name: http
    port: 8900
    targetPort: 8900
  selector:
    app: guides
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guides
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guides
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: guides
    spec:
      automountServiceAccountToken: false
      containers:
      - image: gcr.io/automation-cloud-registry/nodescript-guides:0.0.37
        name: guides
        ports:
        - containerPort: 8900
      imagePullSecrets:
      - name: gcp-registry-access
      nodeSelector:
        workload/default: "true"
