apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-infra-cd
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`cd.ns.ubio.dev`)
    priority: 10
    services:
    - name: argocd-server
      namespace: argocd
      port: 80
  - kind: Rule
    match: Host(`cd.ns.ubio.dev`) && Header(`Content-Type`, `application/grpc`)
    priority: 11
    services:
    - name: argocd-server
      namespace: argocd
      port: 80
      scheme: h2c
  tls:
    secretName: ubio-dev-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-infra-grafana
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`grafana.ns.ubio.dev`)
    services:
    - name: grafana
      namespace: monitoring
      port: 3000
  tls:
    secretName: ubio-dev-certificate
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-infra-prometheus
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`prom.ns.ubio.dev`)
    services:
    - name: prometheus
      namespace: monitoring
      port: 9090
  tls:
    secretName: ubio-dev-certificate
