apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  - group: '*'
    kind: ClusterIssuer
  destinations:
  - namespace: default
    server: '*'
  - namespace: argocd
    server: '*'
  - namespace: cert-manager
    server: '*'
  - namespace: monitoring
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: infrastructure
  source:
    path: infra/certificates/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: infrastructure
  source:
    path: infra/routing/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: infrastructure
  source:
    path: infra/traefik/manifests/production/
    repoURL: git@github.com:NodeScriptLang/infrastructure.git
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
