apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  namespace: argocd
  name: apps
spec:
  destinations:
    - server: '*'
      namespace: default
    - server: '*'
      namespace: argocd
  sourceRepos:
    - '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
