kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend
    newTag: 6.16.3
resources:
  - ../../base
  - ./hpa.yaml
  - ./pdb.yaml
configMapGenerator:
  - name: api-service-config
    literals:
      - GRAPH_SOURCE_URL=https://nodescript.dev/graph/{graphId}
      - LOG_LEVEL=info
      - NODESCRIPT_SLACK_ENDPOINT=https://aat1o4t6.run.nodescript.dev/integrations/slack/post-stripe-payment-result
      - NS_FRONTEND_URL=https://nodescript.dev
      - REGISTRY_URL=https://registry.nodescript.dev
      - STRIPE_BILLING_PORTAL_ID=bpc_1P1CjOK3j0VnFpMHImKAuxrn
      - WORKSPACE_DOMAIN_PATTERN={id}.run.nodescript.dev
