kind: Kustomization

namespace: default

images:
  - name: traefik
    newName: traefik
    newTag: 2.10.5

resources:
  - ../../base
  - pdb.yaml

patches:
  - path: resources.yaml
  - path: replicas.yaml
  - path: service-ips.yaml
