apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
stringData:
    dex.github.clientId: ENC[AES256_GCM,data:JGlosxSvRyMX19fd05f4dVsWJFQ=,iv:tfs0iGtQJRPM8bT8WObBFmZwW5IvAQDGmqcCfImsxmI=,tag:+ejYNtE7y/rh0wATm2Ih/A==,type:str]
    dex.github.clientSecret: ENC[AES256_GCM,data:quicjCIukVZ95m4AsNQilPRr2s4bCK+2GA85TexPwuO7tV6ytxVTPA==,iv:2p78MREPMZL8eG9lJZWExoGZ04bix/cJTtTPFDkWN30=,tag:HAhxaKXkMlhe1QFriQg2tg==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:IC6KBjXM/s1h/YMUa5k8zw==,iv:nRIAiKLYcGZj+2n1kTJln8EQJEs9KOzBZXqMB21y+Ck=,tag:ZJc9D/m2iRlWOl+qTFA0XA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-25T13:38:41Z"
          enc: CiQAlXZeeQFTyb3esd09ODPYOQMEB5/USH56ecMz1HGIbptSJd4SSABnOh03eEiaiqWBYIswxbHeDSV3Mcbp6DFjxdw7NjfwR3rKfahr8giteBgpvB2LMP6lXVvMtT4mYEmz+SiN2l+KXCB7/VnNBw==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-25T13:38:41Z"
    mac: ENC[AES256_GCM,data:G/ISo9usLnxIsz4oKSSYnrwPfP8KRVl0+CZbhstaSTUNDW5Z2FBaDQd8cTIkm8J0dOAoJRq5J5VTwim+qbmXd6srBshpgKVEZO34CzP1I31ah9rdNqaml2S8zmQgK5MO/N9uZ4IcQTOUqTTeIYgzNRmrSpTSOTvijqS3q8JCOLc=,iv:m/mM+Ck5pxuUp0/EtUHkLiQj393mj8/EmpcxYSQjrbY=,tag:sXngMRWZl7daqmGMpJoBfg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
