apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: cloudflare-api-tokens
    annotations:
        description: |-
            The token-ubio-dev allows managing `ubio.dev` zone.

            You probably do not need any other tokens, because ClusterIssuer
            is set up to use CNAME follow strategy.
            If you want to add more domains, add a CNAME to it:

            _acme-challenge.mycool.domain IN CNAME _acme-challenge.ubio.dev.
type: Opaque
stringData:
    token-ubio-dev: ENC[AES256_GCM,data:T0rpo4+YXC9IwTINylHp24aD0yqkXkB/au2R+rmKXfciJ8eSCViA0Q==,iv:TLPXknROwRzPX1DIIdd0Zm+cjndzYowXSRfMjFxU6JA=,tag:BOfOAF3W7pwBrcdtTCM8rA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-25T13:40:17Z"
          enc: CiQAlXZeebkwBpx2mdt7uhizrNPwjhvUGF5fmSDPRAvVLNxE0akSSQBnOh03D7iZF6jDoNIBXGsqumJFBtpBOJQ8Bt5rTQ+vMdMUqqZGg0CcAyva94raZ4C7jgCe8LMCt+2tpVW2hJWPG8UOXnpfdh0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-25T13:40:18Z"
    mac: ENC[AES256_GCM,data:1Y3ts9RfK6q4kmeACtxU/g6vqmn7BWL6SX1e8Q92S2VrWZ9QB/IyCd9Gzsva/i2ORvqb49cU6aUDKbfSdmrpJVIPqvfOyxlQjLXCVwn8jiRZ8H3vAc3/eJOg07shlcoHRe0PzK5JFgJXbeJPBe4pdoar1hZSE3eHB0548+x+0og=,iv:o2JOm6Cy1SVIPBP4+v+yILm3WsZjDbp8qL+qkGUDmSw=,tag:ReLKjyK275nyJDCxbTC+9A==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
