apiVersion: v1
kind: Secret
metadata:
    namespace: monitoring
    name: grafana-secrets
type: Opaque
stringData:
    GF_DATABASE_URL: ENC[AES256_GCM,data:LbryQgYqXBalH9yF3EOYRJBW3wM0V0lGbCd+GHHTp/H7u0wmIwT6SfllEt6ttRPWXvwDdv2w0DDohw==,iv:CvMm/5ERWoyrgAXuMsAC4mmdGWyYd362VtDbZHr/mGw=,tag:PW8QPw7HpstGzOl0U5fyUA==,type:str]
    GF_SERVER_DOMAIN: ENC[AES256_GCM,data:y49A1XqzFRjbBCKtMCwOvp4QTA==,iv:z1SuODQw3Y6KGADidHgAUTKr8P+dOGC9X+0PCt5qUT8=,tag:VNuExrZU0OzGr5dxTaOUow==,type:str]
    GF_SERVER_ROOT_URL: ENC[AES256_GCM,data:Ym1tPspv1n0qZcW4SJFYvdGJ92QArHeWOM2T,iv:e2cmvffBwqSSEh99pyIAFbB08UOykx7+gq1zuHo9IoQ=,tag:0u837rJaeu2WJDXEAcSOig==,type:str]
    GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:bJEpWetCqWC048XPdR/s9nG8d/I=,iv:faW7VhPHL433JIYRjTuVvUvdsbWv/JrgUfjWhOsHVUQ=,tag:5co84UIuOdWoLplYccEdGQ==,type:str]
    GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:5As4OwD4yTiavUR8ghDw0kxnmhxCbK/r4h7vAdpeNuj+5AWnyd7hyA==,iv:BILOx40h0FOYLFXW5utCVnflbcEu5f1J5TRRZ5agZM0=,tag:kOVn46XINRkRlbfoRIT1Ug==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-26T10:01:29Z"
          enc: CiQAlXZeeTZp6TLovF5i2On2PrH8VpY5q6cbe/oleqpJol8qavwSSQBnOh038yH3i+vCvB+/tufUsxaddGXG6SdpV1MCn3mNSG8WUMOoXmfmyYvEYzXcXZTmgCbxMhD+dUekJ/uCj3jE+y9YjJ8HF0k=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-26T10:29:12Z"
    mac: ENC[AES256_GCM,data:hb3eonDgeWD3pLTr1+nbs9kIt1RgnNbcNFgw74lSCS3rbV99rs3TRkXvgCR5kvHkY3cjXG/cI8j6GFNeWyKDlXfUrgBl9KPjkqQXsTnSvfGUj6/lxhO9UIgW1oySX9BoGKUegQOxP48FKo5VcB6vPXYPcMOp4BLC4qs1+7cf0bc=,iv:nCZuFG8bCzc+dMNvEkvEeQaEwILKb3cx9GvWzBurssY=,tag:g8dDCR34xELCnRE99IJdrQ==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
