apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: routing-auth-prometheus
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:tN2dqQ==,iv:qvTX5pdIV5Fx5Xw32HQESRQTQwUchn/VS9BohJ9ONZ8=,tag:BjvfNJSa0b1De13nV8Yfrg==,type:str]
    password: ENC[AES256_GCM,data:stkRbai5tmorLO7386WiDA==,iv:ap829BbmkRm7uG3iwZNFntRGze4ohgyT4U7U2uEidjY=,tag:5IvSGkz3p8uMxeOq2A8qIQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-production/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-26T11:23:55Z"
          enc: CiQAlXZeeVV7cJFZhiO8fvgsG/jN+SAyTy/EN2R9vshMlLi7YM0SSQBnOh030tc6z1LbQISMMJaQTuSefpupCQ1mVBULOWuo6rY1VpQ4MmarCtPcbopZXVbASrWOvaQpBmAcnNgYSqffpVcI0chBzN4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-26T11:23:55Z"
    mac: ENC[AES256_GCM,data:cYDCTd+h932W7WJqoj45ok+zvBDvpcEkmQ+UyDA7tR9RQup2vuRVikYIB9CqK+eTIGT/ypZRo0gHYKLAZryFxxNclVv+wCed7K35rAZMGpd+o2eNbzXsp+xg8XEcluVvVKbjVTyu0ao5mk0aF6hQDeruSvGK4h8qrxZVgcSy8aU=,iv:jNCQXQ5EqPZCsPVqqtjki2FGT81P1vVxCy8gN7OaWqo=,tag:uzZYWHd+uUok8/AX28NA7Q==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
