apiVersion: apps/v1
kind: Deployment
metadata:
  name: background-service
spec:
  selector:
    matchLabels:
      app: background-service
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: background-service
    spec:
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: gcp-registry-access
      nodeSelector:
        workload/default: 'true'
      containers:
        - name: background-service
          image: nodescript-backend
          workingDir: /app/packages/background-service
          command:
            - node
            - out/bin/run.js
          ports:
            # - name: http
            #   containerPort: 8080
            - name: aux
              containerPort: 8081
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              memory: 1000Mi
          env:
            # - name: HTTP_PORT
            #   value: '8080'
            - name: AUX_HTTP_PORT
              value: '8081'
          envFrom:
            - secretRef:
                name: backend-secrets
          readinessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /status
              port: aux
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 5
