kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: eu.gcr.io/automation-cloud-registry/nodescript-backend
    newTag: 4.33.0
resources:
  - ../../base
  - ./pdb.yaml
