apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8081"
  name: capture-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  - name: aux
    port: 8081
    targetPort: aux
  selector:
    app: capture-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capture-service
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: capture-service
  template:
    metadata:
      labels:
        app: capture-service
    spec:
      automountServiceAccountToken: false
      containers:
      - command:
        - node
        - out/bin/run.js
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: AUX_HTTP_PORT
          value: "8081"
        envFrom:
        - secretRef:
            name: backend-secrets
        image: gcr.io/automation-cloud-registry/nodescript-backend:4.33.0
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: capture-service
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: aux
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /status
            port: aux
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 40Mi
        workingDir: /app/packages/capture-service
      imagePullSecrets:
      - name: gcp-registry-access
      nodeSelector:
        workload/default: "true"
      terminationGracePeriodSeconds: 30
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: capture-service
  namespace: default
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: capture-service
