version: "3"

includes:
  kustomize: ../../.tasks/kustomize.yaml
  sed: ../../.tasks/sed.yaml

vars:
  TARGETS: |
    staging
    production
  REPLACEMENTS: |

tasks:
  default:
    silent: true
    cmds:
      - task: kustomize:buildAll
        vars:
          TARGETS: "{{.TARGETS}}"
      - task: sed:replaceAll
        vars:
          REPLACEMENTS: "{{.REPLACEMENTS}}"
