kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend
    newTag: 5.30.0
resources:
  - ../../base
  - ./pdb.yaml
  - ./hpa.yaml
configMapGenerator:
  - name: gateway-service-tiers
    files:
      - tiers.json
