version: "3"

includes:
  kustomize: ../../.tasks/kustomize.yaml
  sed: ../../.tasks/sed.yaml

vars:
  TARGETS: |
    production
    staging

tasks:
  default:
    silent: true
    cmds:
      - task: kustomize:buildAll
        vars:
          TARGETS: "{{.TARGETS}}"
