version: "3"

includes:
  kustomize: ../../.tasks/kustomize.yaml
  sed: ../../.tasks/sed.yaml

vars:
  TARGETS: |
    production
    staging
  REPLACEMENTS: |
    production:RETENTION_TIME,30d
    production:RETENTION_SIZE,80GB
    staging:RETENTION_TIME,2d
    staging:RETENTION_SIZE,8GB

tasks:
  default:
    silent: true
    cmds:
      - task: kustomize:buildAll
        vars:
          TARGETS: "{{.TARGETS}}"
      - task: sed:replaceAll
        vars:
          REPLACEMENTS: "{{.REPLACEMENTS}}"
