apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
stringData:
    dex.github.clientId: ENC[AES256_GCM,data:TCl2+/BI4E9Jh1HqrYuV/hBfywg=,iv:4XZS0GdfAlBKlHxxmsWqHMflEY0h36J+AJsDEZEmD1U=,tag:zgHLn8S61jqGhd9N86HPzA==,type:str]
    dex.github.clientSecret: ENC[AES256_GCM,data:jYNmem1wLetgGrrNSq7GdivuViN8I2nDsfElJobdR55T8ncJ7GG7hw==,iv:wQGB62K54zbxjreQwkDCgD+kxbEIPUdcZPK7IbLvKE4=,tag:bsT+vA9OK4Dz5FGOZn/Uqw==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:xNoHyX+Q9zWbiq2Tqn+eqA==,iv:8UlxYXDDjpOHSW4dZjXGSaL/hq12WF1MfnPNOlzJzjQ=,tag:xi2ugPhX/SS9LIMF+c1wsg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-staging/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-25T13:38:36Z"
          enc: CiQAyUhKO6f05hUD+1zyN6LGlpRK2Uq7hlrCSnABzjk2B88wbigSSQDzK6JNVNp7PUik8taXQ2gVHBTIvklrhszEerhzJeIf21KWquylMjj7JmmMcO/C6fRe/x6v0yy6kwAngnRilSJ0MuaKEaaRoI8=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-25T13:38:36Z"
    mac: ENC[AES256_GCM,data:C1zpOdyJ63s1tffiLId+RXVFHtsXmhb0EPyyBiIKgkIbCuvuv/DQfN7ZJBHOjBWk4lJ5A0qV6p7vKRMvE5ipoyfoxeJLAZ5nTMkYVtHSdw2TGpCwkWELK2ve2fum+abfpHRRLcrGr2ONOCyLXoTOVd8zag9RUmeEFzTqq0s11zw=,iv:NpA6UaZFo+Rq38OutK+XxcvQIR53moWD8xo4zlAs6yk=,tag:blVpgDv/brDfsy95b/oKJA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
