apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: cloudflare-api-tokens
    annotations:
        description: |-
            The token-ubio-dev allows managing `ubio.dev` zone.

            You probably do not need any other tokens, because ClusterIssuer
            is set up to use CNAME follow strategy.
            If you want to add more domains, add a CNAME to it:

            _acme-challenge.mycool.domain IN CNAME _acme-challenge.ubio.dev.
type: Opaque
stringData:
    token-ubio-dev: ENC[AES256_GCM,data:1lyUZKHrIt0bsKMtFADmdQ8dVu8uSQaQb+y/jTbuESEXUJoSg55P1Q==,iv:NPcjEOlWqdvxpKbRjVWLR3uaGc89jk7NBUD1l20Kq7U=,tag:VotkBFpstdJNlK/IKfgpTg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-staging/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-25T13:40:12Z"
          enc: CiQAyUhKO6Gq6WMsHOPq627RslzligoRQEUukpFifM48AODKruwSSQDzK6JNrWs+zzhOLNF/bDWG/1POrh2HsdMw7Wi3UJLVjjsJpHc1tb8bGRhbsblD7N2CRVkdUiy41XmrwlT98IMmc+FwpXhC8GE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-25T13:40:12Z"
    mac: ENC[AES256_GCM,data:NljXZnfF9Nxqzwi/zBY/XoXFfbNZh3ll5VU+VvHjrLoUBCnxFCXRiRlR98XqNvPbLT3/UED3vydmEmj8svUSAL1dqIUJObfe9YAAGsL1HyGwlSTl6moEWrfoRWLPWDzFc+OuLlqN51OTYXR3etQKsOB72kEXQGmZWdRkiVNzhGo=,iv:inOC+pupJ8Xk9Xm0hRxkN1RWOYrFRreNBmqX2P5mJ1c=,tag:r9HUK3Z6/iOSPyUX/qbPtg==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
