apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: routing-auth-prometheus
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:x9QiKA==,iv:71kzbBxz2yk7JDNaTnXnthkRnAHaavQ5MbxaaHDeJ30=,tag:x+v11oE/oixeXeGG6XNwqg==,type:str]
    password: ENC[AES256_GCM,data:Uz+yA4l+JrQ1MnU8Jj9IwQ==,iv:Ea1D9z0Lz1GJk1BU8Y+12ge6jVlzait5QTnTwx5s4xM=,tag:K+gqXN/FwKSxPhQKjFmwSA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/nodescript-staging/locations/europe-west1/keyRings/infra/cryptoKeys/infra-sops-01
          created_at: "2023-10-26T11:24:00Z"
          enc: CiQAyUhKO3fnqc0L1dX8EUGnkNQ9QB6QrEE0YT1Ihv2/nXwXVNYSSQDzK6JN4PMORadTOh0OZNP5smYL4CBDLqomUIwgKSe2k9UAaV9EgjaJPlaW8+ha98KdxoZ5ifGBCsH/6vg/zocGBVa3AG0eHCY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-26T11:24:00Z"
    mac: ENC[AES256_GCM,data:bfkkh8r5LJBm36mSaCL6LeBa+SEvCEy7ZN9J43SqLx4NbT/1/oPXuocwri5o0CDuXYLQwhu+XWWXsJ8KLMya8eprDgnavp1KCt42kQJQm/QaPrX1MW+jrl/k31ysn6vZ/HICq1eHS+15foBBi1o0KaFhVDWi3J+tbnTZ602sY1A=,iv:lZvMdbYneqLCep54sBcTZlMhLFlo8u0QGrXy/lwVk3w=,tag:oDtxY6VCZVVqFMHtB86BeA==,type:str]
    pgp: []
    encrypted_regex: ^(stringData|data)$
    version: 3.8.0
