apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: automation-cloud-certificate
  namespace: default
spec:
  secretName: automation-cloud-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - "automation.cloud"
    - "*.automation.cloud"
    - "*.smartfeed.automation.cloud"
