apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: automation-cloud-certificate
  namespace: default
spec:
  dnsNames:
  - automation.cloud
  - '*.automation.cloud'
  - '*.smartfeed.automation.cloud'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: automation-cloud-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nodescript-dev-certificate
  namespace: default
spec:
  dnsNames:
  - nodescript.dev
  - '*.nodescript.dev'
  - '*.staging.nodescript.dev'
  - '*.adapters.nodescript.dev'
  - '*.adapters.staging.nodescript.dev'
  - '*.edge.nodescript.dev'
  - '*.edge.staging.nodescript.dev'
  - '*.run.nodescript.dev'
  - '*.run.staging.nodescript.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: nodescript-dev-certificate
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ubio-dev-certificate
  namespace: default
spec:
  dnsNames:
  - '*.ns.ubio.dev'
  - '*.staging.ns.ubio.dev'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-issuer
  secretName: ubio-dev-certificate
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: default
spec:
  acme:
    email: dev@ub.io
    privateKeySecretRef:
      name: letsencrypt-issuer-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            key: token-ubio-dev
            name: cloudflare-api-tokens
          email: mg@ub.io
        cnameStrategy: Follow
      selector:
        dnsZones:
        - automationcloud.net
        - automation.cloud
        - nodescript.dev
        - ubio.dev
