kind: Kustomization
namespace: default
images:
  - name: nodescript-backend
    newName: europe-west1-docker.pkg.dev/nodescript-production/nodescript-image-registry/nodescript-backend
    newTag: 6.9.0
resources:
  - ../../base
  - ./hpa.yaml
  - ./pdb.yaml
configMapGenerator:
  - name: ws-service-config
    literals:
      - LOG_LEVEL=info
