apiVersion: v1
kind: Service
metadata:
  annotations:
    metricsPort: "8080"
  name: fetch-service
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: fetch-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-service
  namespace: default
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: fetch-service
  template:
    metadata:
      labels:
        app: fetch-service
    spec:
      automountServiceAccountToken: false
      containers:
      - image: eu.gcr.io/automation-cloud-registry/nodescript-fetch-service:2.7.2
        name: fetch-service
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
      imagePullSecrets:
      - name: gcp-registry-access
      nodeSelector:
        workload/default: "true"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fetch-service
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: fetch-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fetch-service
  namespace: default
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fetch-service
