apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  # https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/#rbac-resources-and-actions
  policy.default: role:readonly
  policy.gh.csv: |
    g, NodeScriptLang:Engineering, role:admin
