apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      nodeSelector:
        workload/ingress: "true"
      serviceAccount: traefik-ingress-controller
      serviceAccountName: traefik-ingress-controller
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 30
      # topologySpreadConstraints:
      # - labelSelector:
      #     matchLabels:
      #       app: traefik
      #   maxSkew: 1
      #   topologyKey: kubernetes.io/hostname
      #   whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: traefik
          args:
          - --serversTransport.insecureSkipVerify=true
          - --accesslog
          - --entryPoints.metrics.address=:8082
          - --entrypoints.websecure.Address=:443
          - --entrypoints.web.Address=:80
          - --entrypoints.web.http.redirections.entryPoint.to=websecure
          - --entrypoints.web.http.redirections.entryPoint.scheme=https
          - --entrypoints.web.http.redirections.entrypoint.permanent=true
          - --providers.kubernetescrd
          - --providers.kubernetescrd.allowCrossNamespace=true
          - --metrics=true
          - --metrics.prometheus=true
          - --metrics.prometheus.entryPoint=metrics
          image: traefik
          lifecycle:
            preStop:
              exec:
                command:
                - sh
                - -c
                - sleep 10s
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /metrics
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 500m
              memory: 500Mi
            limits:
              memory: 1Gi
          securityContext:
            procMount: Default
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
              add: ['NET_BIND_SERVICE']
