apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  selector:
    app: traefik
  ports:
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: secure-proxy
    port: 8001
    protocol: TCP
    targetPort: 8001
