apiVersion: v1
kind: Service
metadata:
  name: traefik
  annotations:
    metricsPort: "8082"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  sessionAffinity: None
  selector:
    app: traefik
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
