kind: Kustomization
namespace: default
images:
  - name: nodescript-fetch-service
    newName: gcr.io/automation-cloud-registry/nodescript-fetch-service
    newTag: 2.7.2
resources:
  - ../../base
  - ./hpa.yaml
  - ./pdb.yaml
