kind: Kustomization

namespace: default

images:
  - name: nodescript-backend
    newName: gcr.io/automation-cloud-registry/nodescript-backend
    newTag: 3.52.0

resources:
  - ../../base
  - ./pdb.yaml
