kind: Service
apiVersion: v1
metadata:
  name: relay-service
  annotations:
    metricsPort: "8081"
spec:
  type: ClusterIP
  selector:
    app: relay-service
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: aux
      port: 8081
      targetPort: aux
