apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-custom-automation-cloud-services
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`[0-9a-z-]+.automation.cloud`)
      services:
        - name: gateway-service
          port: 8080
    - kind: Rule
      match: HostRegexp(`[0-9a-z-]+.smartfeed.automation.cloud`)
      services:
        - name: gateway-service
          port: 8080
  tls:
    secretName: automation-cloud-certificate
