apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: route-custom-automation-cloud-services
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      syntax: v2
      match: HostRegexp(`{subdomain:[0-9a-z-]+}.automation.cloud`)
      services:
        - name: gateway-service
          port: 8080
    - kind: Rule
      match: HostRegexp(`{subdomain:[0-9a-z-]+}.smartfeed.automation.cloud`)
      syntax: v2
      services:
        - name: gateway-service
          port: 8080
  tls:
    secretName: automation-cloud-certificate
